#!/bin/sh

VERSION=1.0
INSTALLDIR=/home/apps/SiteMonitor
CONFIGDIR="$INSTALLDIR/etc"
LOGDIR=$INSTALLDIR/log
LOGFILE=Transact.log
LOGDATEFORMAT="+[%Y/%m/%d_%H:%M:%S]"
WORKDIR=$INSTALLDIR/work
SITELIST=$CONFIGDIR/sitelist.cfg
ALERTCONFIG=$CONFIGDIR/alertconfig.cfg
ERRORCONFIG=$CONFIGDIR/errorconfig.cfg
SQLHOST=127.0.0.1
SQLUSER=sitemon
SQLPASSWORD=sitemon
SQLFILE=$INSTALLDIR/work/run.sql
SQLDATABASE=SiteMonitor

